# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/corinsandford/ARPG/DRRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/corinsandford/ARPG/DRRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/corinsandford/ARPG/DRRT/CMakeFiles /Users/corinsandford/ARPG/DRRT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/corinsandford/ARPG/DRRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named drrt

# Build rule for target.
drrt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drrt
.PHONY : drrt

# fast build rule for target.
drrt/fast:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/build
.PHONY : drrt/fast

src/drrt.o: src/drrt.cpp.o

.PHONY : src/drrt.o

# target to build an object file
src/drrt.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/drrt.cpp.o
.PHONY : src/drrt.cpp.o

src/drrt.i: src/drrt.cpp.i

.PHONY : src/drrt.i

# target to preprocess a source file
src/drrt.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/drrt.cpp.i
.PHONY : src/drrt.cpp.i

src/drrt.s: src/drrt.cpp.s

.PHONY : src/drrt.s

# target to generate assembly for a file
src/drrt.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/drrt.cpp.s
.PHONY : src/drrt.cpp.s

src/edge.o: src/edge.cpp.o

.PHONY : src/edge.o

# target to build an object file
src/edge.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/edge.cpp.o
.PHONY : src/edge.cpp.o

src/edge.i: src/edge.cpp.i

.PHONY : src/edge.i

# target to preprocess a source file
src/edge.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/edge.cpp.i
.PHONY : src/edge.cpp.i

src/edge.s: src/edge.cpp.s

.PHONY : src/edge.s

# target to generate assembly for a file
src/edge.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/edge.cpp.s
.PHONY : src/edge.cpp.s

src/ghostPoint.o: src/ghostPoint.cpp.o

.PHONY : src/ghostPoint.o

# target to build an object file
src/ghostPoint.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/ghostPoint.cpp.o
.PHONY : src/ghostPoint.cpp.o

src/ghostPoint.i: src/ghostPoint.cpp.i

.PHONY : src/ghostPoint.i

# target to preprocess a source file
src/ghostPoint.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/ghostPoint.cpp.i
.PHONY : src/ghostPoint.cpp.i

src/ghostPoint.s: src/ghostPoint.cpp.s

.PHONY : src/ghostPoint.s

# target to generate assembly for a file
src/ghostPoint.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/ghostPoint.cpp.s
.PHONY : src/ghostPoint.cpp.s

src/heap.o: src/heap.cpp.o

.PHONY : src/heap.o

# target to build an object file
src/heap.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/heap.cpp.o
.PHONY : src/heap.cpp.o

src/heap.i: src/heap.cpp.i

.PHONY : src/heap.i

# target to preprocess a source file
src/heap.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/heap.cpp.i
.PHONY : src/heap.cpp.i

src/heap.s: src/heap.cpp.s

.PHONY : src/heap.s

# target to generate assembly for a file
src/heap.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/heap.cpp.s
.PHONY : src/heap.cpp.s

src/jlist.o: src/jlist.cpp.o

.PHONY : src/jlist.o

# target to build an object file
src/jlist.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/jlist.cpp.o
.PHONY : src/jlist.cpp.o

src/jlist.i: src/jlist.cpp.i

.PHONY : src/jlist.i

# target to preprocess a source file
src/jlist.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/jlist.cpp.i
.PHONY : src/jlist.cpp.i

src/jlist.s: src/jlist.cpp.s

.PHONY : src/jlist.s

# target to generate assembly for a file
src/jlist.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/jlist.cpp.s
.PHONY : src/jlist.cpp.s

src/kdtree.o: src/kdtree.cpp.o

.PHONY : src/kdtree.o

# target to build an object file
src/kdtree.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/kdtree.cpp.o
.PHONY : src/kdtree.cpp.o

src/kdtree.i: src/kdtree.cpp.i

.PHONY : src/kdtree.i

# target to preprocess a source file
src/kdtree.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/kdtree.cpp.i
.PHONY : src/kdtree.cpp.i

src/kdtree.s: src/kdtree.cpp.s

.PHONY : src/kdtree.s

# target to generate assembly for a file
src/kdtree.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/kdtree.cpp.s
.PHONY : src/kdtree.cpp.s

src/list.o: src/list.cpp.o

.PHONY : src/list.o

# target to build an object file
src/list.cpp.o:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/list.cpp.o
.PHONY : src/list.cpp.o

src/list.i: src/list.cpp.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.cpp.i:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/list.cpp.i
.PHONY : src/list.cpp.i

src/list.s: src/list.cpp.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.cpp.s:
	$(MAKE) -f CMakeFiles/drrt.dir/build.make CMakeFiles/drrt.dir/src/list.cpp.s
.PHONY : src/list.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... drrt"
	@echo "... src/drrt.o"
	@echo "... src/drrt.i"
	@echo "... src/drrt.s"
	@echo "... src/edge.o"
	@echo "... src/edge.i"
	@echo "... src/edge.s"
	@echo "... src/ghostPoint.o"
	@echo "... src/ghostPoint.i"
	@echo "... src/ghostPoint.s"
	@echo "... src/heap.o"
	@echo "... src/heap.i"
	@echo "... src/heap.s"
	@echo "... src/jlist.o"
	@echo "... src/jlist.i"
	@echo "... src/jlist.s"
	@echo "... src/kdtree.o"
	@echo "... src/kdtree.i"
	@echo "... src/kdtree.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

